spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/thymeleaf_tutorial"
    username: postgres
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update

logging.level.org.hibernate:
  SQL: DEBUG
  type: TRACE


